# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metery < Formula
  desc "Self-hosted metering and entitlements backend"
  homepage "https://github.com/meterysh/metery"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meterysh/metery/releases/download/v0.4.0/metery_0.4.0_darwin_amd64.tar.gz"
      sha256 "6575b39b3305ff6c54dce054f57651fa7f78e4342404cee4bb00e11627dd11bd"

      define_method(:install) do
        bin.install "metery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meterysh/metery/releases/download/v0.4.0/metery_0.4.0_darwin_arm64.tar.gz"
      sha256 "d6c2f1dd3bb77219cdca2018976dd181403b99aa408d21a4c1da14c07d53a710"

      define_method(:install) do
        bin.install "metery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meterysh/metery/releases/download/v0.4.0/metery_0.4.0_linux_amd64.tar.gz"
      sha256 "eae42695ccbe069437c71aee0ded03cb38572a3d8c68452308e1ef64963541fb"
      define_method(:install) do
        bin.install "metery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meterysh/metery/releases/download/v0.4.0/metery_0.4.0_linux_arm64.tar.gz"
      sha256 "7a27411551410d7e70e0d1900b21136e80a73b7e524083296f89bf785951e001"
      define_method(:install) do
        bin.install "metery"
      end
    end
  end
end
