# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metery < Formula
  desc "Self-hosted usage-billing and entitlements backend"
  homepage "https://github.com/meterysh/metery"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meterysh/metery/releases/download/v0.2.0/metery_0.2.0_darwin_amd64.tar.gz"
      sha256 "5c8cd10bfc1eb301e99fb69a53ff4b2ebe24cf64808ee64ea72233969b9bb855"

      define_method(:install) do
        bin.install "metery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meterysh/metery/releases/download/v0.2.0/metery_0.2.0_darwin_arm64.tar.gz"
      sha256 "d70f506cfa09936cc89cd224004a3ddf775869709ef049d5db2de65531b0329b"

      define_method(:install) do
        bin.install "metery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meterysh/metery/releases/download/v0.2.0/metery_0.2.0_linux_amd64.tar.gz"
      sha256 "c7ceea39fa6ecd02d1855dbeaac22e187cba6320d67b0cd86cdae6ec800d4c24"
      define_method(:install) do
        bin.install "metery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meterysh/metery/releases/download/v0.2.0/metery_0.2.0_linux_arm64.tar.gz"
      sha256 "8662784d3acd5a0dc1107ef2bb229d90532b0b4e78078b1267f5984523c9b2fc"
      define_method(:install) do
        bin.install "metery"
      end
    end
  end
end
